/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vault.glb -T 
Files: vault.glb [24.4MB] > /Users/shivamrawat/Cognizance/Frontend/public/vault-transformed.glb [1.57MB] (94%)
Author: Levi Moresi (https://sketchfab.com/LeviJM)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-steampunk-vault-b381d06f61d44b77bfe666582b5e44e9
Title: The Steampunk Vault
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/vault-transformed.glb')
  const { actions } = useAnimations(animations, group)


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Animated" scale={0.01}>
          <group name="Robot" position={[2.687, 2.478, -3.845]}>
            <group name="Interior_Lining" position={[-2.633, -0.042, 3.845]}>
              <mesh name="Interior_Lining_Chest_Material_0" geometry={nodes.Interior_Lining_Chest_Material_0.geometry} material={materials.Chest_Material} />
            </group>
            <group name="Robot_1" position={[-2.661, 0.258, 3.807]}>
              <mesh name="Robot_Robot_Material_0" geometry={nodes.Robot_Robot_Material_0.geometry} material={materials.Robot_Material} />
            </group>
          </group>
          <group name="Bolt2" position={[3.529, 3.195, 1.97]}>
            <mesh name="Bolt2_Chest_Material_0" geometry={nodes.Bolt2_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Bolt1" position={[3.529, 3.195, -1.97]}>
            <mesh name="Bolt1_Chest_Material_0" geometry={nodes.Bolt1_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Chest_Lid" position={[-3.604, 3.421, -3.234]}>
            <group name="Lid_Interior" position={[3.604, 0.472, 3.234]}>
              <mesh name="Lid_Interior_Chest_Material_0" geometry={nodes.Lid_Interior_Chest_Material_0.geometry} material={materials.Chest_Material} />
            </group>
            <group name="Chest_Lid_1" position={[3.704, 1.242, 3.234]}>
              <mesh name="Chest_Lid_Chest_Material_0" geometry={nodes.Chest_Lid_Chest_Material_0.geometry} material={materials.Chest_Material} />
            </group>
            <group name="Lid_Bar_Locks" position={[3.604, 1.522, 3.234]}>
              <group name="Lock1" position={[0.442, 0, 3.615]}>
                <mesh name="Lock1_Chest_Material_0" geometry={nodes.Lock1_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="Lock2" position={[-0.442, 0, 3.615]}>
                <mesh name="Lock2_Chest_Material_0" geometry={nodes.Lock2_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="Lock3" position={[-0.442, 0, -3.615]}>
                <mesh name="Lock3_Chest_Material_0" geometry={nodes.Lock3_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="Lock4" position={[0.442, 0, -3.615]}>
                <mesh name="Lock4_Chest_Material_0" geometry={nodes.Lock4_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
            </group>
            <group name="Back_Hinges" position={[0.381, 0.186, 3.234]}>
              <mesh name="Back_Hinges_Chest_Material_0" geometry={nodes.Back_Hinges_Chest_Material_0.geometry} material={materials.Chest_Material} />
            </group>
            <group name="Buttons" position={[7.067, 0.741, 0.558]}>
              <group name="_2" position={[-0.062, 0.175, 0]}>
                <mesh name="_2_Chest_Material_0" geometry={nodes._2_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="_3" position={[-0.102, 0.175, -0.173]}>
                <mesh name="_3_Chest_Material_0" geometry={nodes._3_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="_4" position={[-0.062, 0, 0.173]}>
                <mesh name="_4_Chest_Material_0" geometry={nodes._4_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="_6" position={[-0.062, 0, -0.173]}>
                <mesh name="_6_Chest_Material_0" geometry={nodes._6_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="_8" position={[-0.062, -0.175, 0]}>
                <mesh name="_8_Chest_Material_0" geometry={nodes._8_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="_1" position={[-0.062, 0.175, 0.173]}>
                <mesh name="_1_Chest_Material_0" geometry={nodes._1_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="_5" position={[-0.062, 0, 0]}>
                <mesh name="_5_Chest_Material_0" geometry={nodes._5_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="_7" position={[-0.062, -0.175, 0.173]}>
                <mesh name="_7_Chest_Material_0" geometry={nodes._7_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="_9" position={[-0.062, -0.175, -0.173]}>
                <mesh name="_9_Chest_Material_0" geometry={nodes._9_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
            </group>
            <group name="Gears" position={[3.604, -3.421, 3.234]}>
              <group name="Gear1" position={[2.759, 4.164, 4.299]}>
                <mesh name="Gear1_Chest_Material_0" geometry={nodes.Gear1_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="Gear2" position={[2.759, 4.164, -4.299]}>
                <mesh name="Gear2_Chest_Material_0" geometry={nodes.Gear2_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="Gear3" position={[-2.759, 4.164, 4.299]}>
                <mesh name="Gear3_Chest_Material_0" geometry={nodes.Gear3_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
              <group name="Gear4" position={[-2.759, 4.164, -4.299]}>
                <mesh name="Gear4_Chest_Material_0" geometry={nodes.Gear4_Chest_Material_0.geometry} material={materials.Chest_Material} />
              </group>
            </group>
          </group>
        </group>
        <group name="Springs" scale={0.01}>
          <group name="L_Top" position={[0.009, 0.841, -5.966]}>
            <mesh name="L_Top_Chest_Material_0" geometry={nodes.L_Top_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="L_Bot" position={[0.009, 0.841, 5.966]}>
            <mesh name="L_Bot_Chest_Material_0" geometry={nodes.L_Bot_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="R_Top" position={[0.01, 3.705, -5.966]}>
            <mesh name="R_Top_Chest_Material_0" geometry={nodes.R_Top_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="R_Bot" position={[0.01, 3.705, 5.966]}>
            <mesh name="R_Bot_Chest_Material_0" geometry={nodes.R_Bot_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
        </group>
        <group name="Front_Valve" scale={0.01}>
          <group name="Knob" position={[3.034, 1.032, 0.621]}>
            <mesh name="Knob_Chest_Material_0" geometry={nodes.Knob_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
        </group>
        <group name="L_Gears" scale={0.01}>
          <group name="Large1" position={[3.018, 1.424, 3.681]}>
            <mesh name="Large1_Chest_Material_0" geometry={nodes.Large1_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Large2" position={[3.018, 2.071, 2.574]}>
            <mesh name="Large2_Chest_Material_0" geometry={nodes.Large2_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Medium" position={[2.99, 2.886, 3.533]}>
            <mesh name="Medium_Chest_Material_0" geometry={nodes.Medium_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Small1" position={[2.944, 2.318, 3.245]}>
            <mesh name="Small1_Chest_Material_0" geometry={nodes.Small1_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Small2" position={[2.927, 2.288, 3.801]}>
            <mesh name="Small2_Chest_Material_0" geometry={nodes.Small2_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Small3" position={[2.927, 2.754, 2.77]}>
            <mesh name="Small3_Chest_Material_0" geometry={nodes.Small3_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
        </group>
        <group name="R_Gears" scale={0.01}>
          <group name="Large1_1" position={[3.018, 1.424, -3.681]}>
            <mesh name="Large1_Chest_Material_0_1" geometry={nodes.Large1_Chest_Material_0_1.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Large2_1" position={[3.018, 2.071, -2.574]}>
            <mesh name="Large2_Chest_Material_0_1" geometry={nodes.Large2_Chest_Material_0_1.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Medium_1" position={[2.99, 2.886, -3.533]}>
            <mesh name="Medium_Chest_Material_0_1" geometry={nodes.Medium_Chest_Material_0_1.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Small1_1" position={[2.944, 2.318, -3.245]}>
            <mesh name="Small1_Chest_Material_0_1" geometry={nodes.Small1_Chest_Material_0_1.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Small2_1" position={[2.927, 2.288, -3.801]}>
            <mesh name="Small2_Chest_Material_0_1" geometry={nodes.Small2_Chest_Material_0_1.geometry} material={materials.Chest_Material} />
          </group>
          <group name="Small3_1" position={[2.927, 2.754, -2.77]}>
            <mesh name="Small3_Chest_Material_0_1" geometry={nodes.Small3_Chest_Material_0_1.geometry} material={materials.Chest_Material} />
          </group>
        </group>
        <group name="Locking_Mechanism" scale={0.01}>
          <group name="Lock_Head" position={[3.645, 3.454, 0]}>
            <group name="Lock_Handle1" position={[0.819, -0.043, -0.001]}>
              <mesh name="Lock_Handle1_Chest_Material_0" geometry={nodes.Lock_Handle1_Chest_Material_0.geometry} material={materials.Chest_Material} />
            </group>
            <group name="Lock_Handle2" position={[0.819, -0.043, -0.001]}>
              <mesh name="Lock_Handle2_Chest_Material_0" geometry={nodes.Lock_Handle2_Chest_Material_0.geometry} material={materials.Chest_Material} />
            </group>
            <group name="Lock_Handle3" position={[0.819, -0.043, -0.001]}>
              <mesh name="Lock_Handle3_Chest_Material_0" geometry={nodes.Lock_Handle3_Chest_Material_0.geometry} material={materials.Chest_Material} />
            </group>
            <group name="Lock_Handle4" position={[0.819, -0.043, -0.001]}>
              <mesh name="Lock_Handle4_Chest_Material_0" geometry={nodes.Lock_Handle4_Chest_Material_0.geometry} material={materials.Chest_Material} />
            </group>
            <group name="Mount" position={[-0.225, 0, 0]}>
              <mesh name="Mount_Chest_Material_0" geometry={nodes.Mount_Chest_Material_0.geometry} material={materials.Chest_Material} />
            </group>
          </group>
          <group name="L_Lock_Bar" position={[3.133, 3.418, 0.843]}>
            <mesh name="L_Lock_Bar_Chest_Material_0" geometry={nodes.L_Lock_Bar_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
          <group name="R_Lock_Bar" position={[3.133, 3.074, -1.634]}>
            <mesh name="R_Lock_Bar_Chest_Material_0" geometry={nodes.R_Lock_Bar_Chest_Material_0.geometry} material={materials.Chest_Material} />
          </group>
        </group>
        <mesh name="Side_Support_Chest_Material_0" geometry={nodes.Side_Support_Chest_Material_0.geometry} material={materials.Chest_Material} scale={0.01} />
        <mesh name="Head_RobotHead_0" geometry={nodes.Head_RobotHead_0.geometry} material={materials.RobotHead} position={[0, 0.068, 0.007]} rotation={[-2.945, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/vault-transformed.glb')
